### ISSUE TITLE
Error escaping special character

### ISSUE THREAD

**Issue by kastanekdavid** [Seldaek/jsonlint#39]
Bad parsing of escape character. Escape tag is not properly parsed so the special character isn't escaped. Instead it throws exception:

```
... does not contain valid JSON
Parse error on line xxx:
.../nette.org/donate": "[1;37;42m Please c
----------------------^
Invalid string, it appears you forgot to terminate a string, or attempted to write a multiline string which is invalid
```

**Comment by stof** [comment]
Can you give the corresponding JSON ?

**Comment by kastanekdavid** [comment]
The issue is connected to a [problem with PHP5.3](http://phpsadness.com/sad/20) not being able to properly parse escape characters. Upgrading PHP should resolve the problem. Sorry to bother you. :)
