### ISSUE TITLE
Allow comments

### ISSUE THREAD

**Issue by iandunn** [Seldaek/jsonlint#58]
I'm not sure how closely you want to track `zaach/jsonlint`, but [they have an open issue for this](https://github.com/zaach/jsonlint/issues/50) as well.

-----

Comments aren't technically _valid_, but I wouldn't say they're _invalid_ either. 

Douglas Crockford (creator of JSON) [has said](https://web.archive.org/web/20100629021329/http://blog.getify.com/2010/06/json-comments/): 

> A JSON encoder MUST NOT output comments. A JSON decoder MAY accept and ignore comments.

Comments were initially allowed in JSON, and [were only removed to prevent people from adding parsing directives](https://web.archive.org/web/20190112173904/https://plus.google.com/118095276221607585885/posts/RK8qyGVaGSr).

They're very useful in things like `composer.json` files, where there can sometimes be important things to document.

There's no reason that decoders can't allow and ignore them. Since some do just that, I think it makes sense for JSON linters to provide a flag that will let them pass through as well. The user will know best what their particular use case allows.

**Comment by Seldaek** [comment]
I'm not strictly against supporting it here either as long as it's behind a feature flag.

**Comment by stof** [comment]
Even allowing comments behind a flag won't allow you to put JS comments in the composer.json. For performance reasons, Composer uses PHP's `json_decode` to read JSON files. It uses this library only to provide a better error message in case of failure.
