### ISSUE TITLE
Weird parsing of unicode characters

### ISSUE THREAD

**Issue by theofidry** [Seldaek/jsonlint#59]
Given the following JSON:

```json
{
  "errors": [
    {
      "message": "Argument \u0022input\u0022 has an invalid value: ...."
    }
  ]
}
```

(for some reason a mink driver is returning this instead of `\"`...)

With `json_decode()` you will get:

```
{#4
  +"errors": array:1 [
    0 => {#5
      +"message": "Argument "input" has an invalid value: ...."
    }
  ]
}
```

However with `JsonParser` you will get:

```
{#17
  +"errors": array:1 [
    0 => {#16
      +"message": "Argument &#x22;input&#x22; has an invalid value: ...."
    }
  ]
}
```

Any idea of how this could be fixed?

**Comment by Seldaek** [comment]
Looks like possibly a bug in https://github.com/Seldaek/jsonlint/blob/master/src/Seld/JsonLint/JsonParser.php#L471 - have a look?

**Comment by theofidry** [comment]
Will try, thanks for the pointer

**Comment by theofidry** [comment]
For my future self, might be of some help: https://github.com/zaach/jsonlint/pull/54
