### ISSUE TITLE
Don't ship tests and supporting files etc.

### ISSUE THREAD

**Issue by willemstuursma** [Seldaek/jsonlint#68]
I noticed that when installing this through composer the tests are also part of the package.

Will you accept a PR to remove tests and supporting files from the distributions? If so, I will create one. 

I know not everyone likes that, hence I'm asking first.

**Comment by Seldaek** [comment]
Yeah that'd be fine thanks

**Comment by Seldaek** [comment]
Fixed by https://github.com/Seldaek/jsonlint/pull/77

**Comment by willemstuursma** [comment]
Thanks, I'm sorry I missed the notification from May 20th.
