### ISSUE TITLE
bump changelog after `1.8.1`

### ISSUE THREAD

**Issue by jnkowa-gfk** [Seldaek/jsonlint#78]
Hello @Seldaek ,

the https://github.com/Seldaek/jsonlint/blob/main/CHANGELOG.md
is missing releases after `1.8.1`.

the list of releases does not help, either.

**Comment by Seldaek** [comment]
https://github.com/Seldaek/jsonlint/releases contains all changelogs.

**Comment by jnkowa-gfk** [comment]
thanks to https://github.com/Seldaek/jsonlint/commit/a094f1aaa129f86147d10f41033504a9a286e567
my questions are clear, now.
